# Generated by Django 4.0.4 on 2022-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWN', 'Owner'), ('DIS', 'Dispatcher'), ('UPD', 'Updater')], default='DIS', max_length=3),
            preserve_default=False,
        ),
    ]
