# Generated by Django 4.0.4 on 2022-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWN', 'Owner'), ('ADM', 'Admin'), ('DIS', 'Dispatcher'), ('UPD', 'Updater')], max_length=3),
        ),
    ]
