# Generated by Django 4.1.6 on 2023-02-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='editdriver',
            name='is_active',
        ),
    ]
