# Generated by Django 4.1 on 2022-09-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-02'),
            preserve_default=False,
        ),
    ]
