# Generated by Django 4.1.6 on 2023-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_name',
            field=models.CharField(choices=[('dri', 'driver'), ('use', 'user'), ('gro', 'gross'), ('car', 'carrier'), ('veh', 'vehicle'), ('tra', 'trailer'), ('lin', 'invite link')], max_length=3),
        ),
    ]
