# Generated by Django 4.0.4 on 2022-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='?', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='??', max_length=20),
            preserve_default=False,
        ),
    ]
