# Generated by Django 4.0.4 on 2022-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gross_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000.0, max_digits=9),
        ),
    ]
