# Generated by Django 4.1.4 on 2023-01-30 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada')], default='US', max_length=2)),
                ('region', models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], default='AK', max_length=2)),
                ('city', models.CharField(max_length=127)),
                ('zip_code', models.CharField(max_length=15)),
                ('time_zone', models.CharField(choices=[('US/Cent', 'US/Central'), ('US/East', 'US/Eastern'), ('US/Moun', 'US/Mountain'), ('US/Paci', 'US/Pacific')], default='US/East', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(choices=[('Y99', '1999'), ('Y00', '2000'), ('Y01', '2001'), ('Y02', '2002'), ('Y03', '2003'), ('Y04', '2004'), ('Y05', '2005'), ('Y06', '2006'), ('Y07', '2007'), ('Y08', '2008'), ('Y09', '2009'), ('Y10', '2010'), ('Y11', '2011'), ('Y12', '2012'), ('Y13', '2013'), ('Y14', '2014'), ('Y15', '2015'), ('Y16', '2016'), ('Y17', '2017'), ('Y18', '2018'), ('Y19', '2019'), ('Y20', '2020'), ('Y21', '2021'), ('Y22', '2022'), ('Y23', '2023'), ('Y24', '2024'), ('Y24', '2025'), ('Y24', '2026')], default='23', max_length=3),
        ),
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('view_user', models.BooleanField(default=False)),
                ('create_user', models.BooleanField(default=False)),
                ('update_user', models.BooleanField(default=False)),
                ('activate_user', models.BooleanField(default=False)),
                ('view_driver', models.BooleanField(default=False)),
                ('create_driver', models.BooleanField(default=False)),
                ('update_driver', models.BooleanField(default=False)),
                ('activate_driver', models.BooleanField(default=False)),
                ('view_vehicle', models.BooleanField(default=False)),
                ('create_vehicle', models.BooleanField(default=False)),
                ('update_vehicle', models.BooleanField(default=False)),
                ('activate_vehicle', models.BooleanField(default=False)),
                ('view_driver_log', models.BooleanField(default=False)),
                ('create_driver_log', models.BooleanField(default=False)),
                ('update_driver_log', models.BooleanField(default=False)),
                ('activate_driver_log', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
