# Generated by Django 4.1.6 on 2023-02-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_action_target_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
