# Generated by Django 4.1.6 on 2023-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_driver_is_active_remove_editdriver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editload',
            name='bol_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='editload',
            name='pcs_number',
            field=models.CharField(max_length=16),
        ),
    ]
