# Generated by Django 4.1 on 2022-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(max_length=15),
        ),
    ]
