# Generated by Django 4.1 on 2022-09-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_log_pcs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='autobooker',
            field=models.BooleanField(default=False),
        ),
    ]
