# Generated by Django 4.1.6 on 2023-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_editload_bol_number_alter_editload_pcs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_load', to='api.load'),
        ),
    ]
