# Generated by Django 4.1 on 2022-09-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_log_autobooker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='budget_type',
            field=models.CharField(choices=[('D', 'driver'), ('L', 'lane'), ('R', 'recovery')], max_length=1),
        ),
    ]
