# Generated by Django 4.0.4 on 2022-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_log_dispatcher_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_type',
            field=models.CharField(choices=[('O88', 'Owner operator - 88%'), ('O85', 'Owner operator - 85%'), ('C30', 'Company driver - 30%'), ('C35', 'Company driver - 35%'), ('L', 'Lease operator'), ('R', 'Rental operator')], max_length=3),
        ),
    ]
