# Generated by Django 4.0.4 on 2022-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_driver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gross_target',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=9),
        ),
    ]
