# Generated by Django 4.0.4 on 2022-10-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_driver_gross_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bol_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(max_length=16),
        ),
    ]
