# Generated by Django 4.0.4 on 2022-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_log_date_alter_log_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='date',
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
