# Generated by Django 4.1 on 2022-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
