# Generated by Django 4.0.4 on 2022-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='carrier',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='bol_number',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
