# Generated by Django 4.0.4 on 2022-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_log_pcs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='pcs_number',
            field=models.CharField(max_length=15),
        ),
    ]
